### ISSUE TITLE
Customize cache folder

### ISSUE THREAD

**Issue by pascalgrimaud** [tikui/tikui-core#31]
Link to this ticket:
- https://github.com/jhipster/jhipster-lite/issues/3389

It would be better if this temp folder start with a dot, like `.cache`, so here some suggestions:

- `.cache/`
- `.tikui/`
- `.tikui/cache/`

**Comment by Gnuk** [comment]
To customize inside the `tikuiconfig.json`:

```json
{
  // …
  "cache": "path/to/cache",
}
```
